# Generated by Django 5.1.4 on 2025-02-10 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prep_time', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('difficulty', models.IntegerField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')])),
                ('vegitarian', models.BooleanField()),
                ('recipe_img', models.ImageField(upload_to='recipe/')),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
