# Generated by Django 5.1.4 on 2025-02-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recipes_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_img',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/'),
        ),
    ]
